// <auto-generated />
using System;
using ForexIntelligence.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForexIntelligence.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ForexDbContext))]
    partial class ForexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForexIntelligence.Domain.Entities.Candle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTimeOffset>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<decimal>("Low")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<decimal>("Open")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)");

                    b.Property<DateTimeOffset>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<long>("TickVolume")
                        .HasColumnType("bigint");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("Instrument", "Timeframe", "OpenTime")
                        .IsUnique();

                    b.ToTable("candles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
